version: '3.8'


services:
  #============================================================
  # POSTGRESQL DATABASE
  # ============================================================
  postgres:
    image: postgres:16-alpine
    container_name: ratelimitx-postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=ratelimitx
      - POSTGRES_USER=ratelimitx
      - POSTGRES_PASSWORD=ratelimitx123
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ratelimitx -d ratelimitx"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - ratelimitx-network
  # ============================================================
  # REDIS SERVICE
  # ============================================================
  redis:
    image: redis:7-alpine
    container_name: ratelimitx-redis
    ports: 
      - "6379:6379"
    volumes: 
      - redis-data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - ratelimitx-network


  # ============================================================
  # RATELIMITX APPLICATION
  # ============================================================
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ratelimitx-app
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATA_REDIS_HOST=redis
      - SPRING_DATA_REDIS_PORT=6379
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/ratelimitx
      - SPRING_DATASOURCE_USERNAME=ratelimitx
      - SPRING_DATASOURCE_PASSWORD=ratelimitx123
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - JWT_SECRET=myVeryLongAndSecureSecretKeyForJWTTokenGeneration123456789
    depends_on:
      redis:
        condition: service_healthy
    networks:
      - ratelimitx-network

# ============================================================
# VOLUMES (Persistent Storage)
# ============================================================
volumes:
  redis-data:
  postgres-data:

# ============================================================
# NETWORKS
# ============================================================
networks:
  ratelimitx-network:
    driver: bridge